# -*- coding: utf-8 -*-
"""infer.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1j6drxai4YmZUPu_w14jod6xZqfkFWQJW
"""
import csv
from train import *

best_model = None
with open(ckpt_name, 'rb') as f:
    best_model = torch.load(f)

val_stats = runner.validate(val_batch_gen, best_model, phase_name='val')
test_stats = runner.validate(test_batch_gen, best_model, phase_name='test')

with open('stats.csv', mode='w') as file:
    writer = csv.writer(file)
    writer.writerow(['Phase', 'Accuracy', 'F1 Score'])
    writer.writerow(['Val', val_stats['accuracy'], val_stats['f1']])
    writer.writerow(['Test', test_stats['accuracy'], test_stats['f1']])

print("Val", val_stats, "\n")
print("Test", test_stats, "\n")
